# -*- coding: utf-8 -*-
"""Hindi_NEET_PPT_Creation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q-WvUY6c6K9IedsuzxX7lQoVquiZ7eEi
"""

# =========================
# SHEET-DRIVEN PPT CREATION
# Only process rows where:
#   Column O (PDF File Verification) == "Done"
# Reads:
#   Folder link from Column H
# Writes:
#   PPT link to Column X (only if empty; skips "Not Req.")
# Uses:
#   "Processed Screenshots" subfolder + XLSX inside each Drive folder
#   to create QuestionPPT.pptx
# =========================

!pip install -q pydrive2 pillow pandas openpyxl python-pptx gspread

from google.colab import auth
auth.authenticate_user()

import google.auth, re, os, shutil, time, math
import gspread
import pandas as pd
from PIL import Image

from pydrive2.auth import GoogleAuth
from pydrive2.drive import GoogleDrive
from oauth2client.client import GoogleCredentials

from urllib.parse import urlparse, parse_qs
from pptx import Presentation
from pptx.enum.shapes import MSO_SHAPE_TYPE


# ---------------- CONFIG ----------------
SPREADSHEET_ID = "1ISqfQjasbOvB72App7Y62SxOkKIrZxa_kr7mIMQgQ2A"
WORKSHEET_NAME = "NEET Exercises Files"   # "" = first tab

COL_FOLDER       = "H"   # Drive folder link
COL_PDF_VERIFY   = "O"   # PDF File Verification
COL_PPT_LINK     = "X"   # PPT Link (write here)

TEMPLATE_FOLDER_URL = "https://drive.google.com/drive/u/0/folders/1hDMcbSc2PJeM9-LWAXgxKfm1TfRHAdXr"
TEMPLATE_PPTX_NAME = ""  # optional exact file name (else first .pptx in folder)

ANCHOR_SHAPE_NAME = "SCREENSHOT_BOX"

FINAL_PPT_NAME = "QuestionPPT.pptx"
TEMP_PPT_NAME  = "QuestionPPT__INPROGRESS.pptx"

# NEW: images come from this subfolder (inside each Drive folder)
PROCESSED_SCREENSHOTS_FOLDER_NAME = "Processed Screenshots"

WHITE_THRESHOLD = 240
CROP_PAD_PX = 20

# Target slide area occupancy (35–40%)
TARGET_FRACTION = 0.325  # midpoint
MIN_FRACTION = 0.30
MAX_FRACTION = 0.35

SLEEP_BETWEEN_FOLDER_SEC = 0.1
# ----------------------------------------


# ---- Sheets auth ----
creds, _ = google.auth.default()
gc = gspread.authorize(creds)
sh = gc.open_by_key(SPREADSHEET_ID)
ws = sh.worksheet(WORKSHEET_NAME) if WORKSHEET_NAME else sh.get_worksheet(0)
print("Using sheet:", sh.title)
print("Using tab  :", ws.title)

# ---- Drive auth ----
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)


# ---------------- Helpers ----------------
def extract_id_from_url(url):
    u = urlparse(url)
    m = re.search(r'/folders/([a-zA-Z0-9_-]+)', url)
    if m: return m.group(1)
    m = re.search(r'/file/d/([a-zA-Z0-9_-]+)', url)
    if m: return m.group(1)
    q = parse_qs(u.query).get('id')
    if q: return q[0]
    raise ValueError("Could not find an ID in this URL.")

def drive_list(q):
    return drive.ListFile({
        'q': q,
        'corpora': 'allDrives',
        'includeItemsFromAllDrives': True,
        'supportsAllDrives': True
    }).GetList()

def list_in_folder(folder_id, pattern=None):
    files = drive_list(f"'{folder_id}' in parents and trashed=false")
    if pattern:
        rx = re.compile(pattern, re.I)
        files = [f for f in files if rx.search(f['title'])]
    return files

def list_by_exact_title(folder_id, title):
    title_esc = title.replace("'", "\\'")
    return drive_list(f"'{folder_id}' in parents and trashed=false and title='{title_esc}'")

def drive_file_link(file_id):
    return f"https://drive.google.com/file/d/{file_id}/view?usp=drive_link"

def col_letter_to_index(letter):
    letter = letter.strip().upper()
    n = 0
    for ch in letter:
        n = n * 26 + (ord(ch) - ord('A') + 1)
    return n

def is_not_required(cell_value) -> bool:
    s = str(cell_value).strip().lower()
    s_compact = re.sub(r'[\s\.]+', '', s)  # remove spaces + dots
    return s_compact == "notreq"

def is_done(cell_value) -> bool:
    s = str(cell_value).strip().lower()
    # Accept "done", "Done ✅", "done - ok", etc.
    return s.startswith("done")

def remove_white(img, thr=WHITE_THRESHOLD):
    img = img.convert('RGBA')
    data = img.getdata()
    new = []
    for (r,g,b,a) in data:
        if r >= thr and g >= thr and b >= thr:
            new.append((255,255,255,0))
        else:
            new.append((r,g,b,a))
    img.putdata(new)
    return img

def crop_to_content_rgba(img_rgba, pad_px=CROP_PAD_PX):
    alpha = img_rgba.split()[-1]
    bbox = alpha.getbbox()
    if not bbox:
        return img_rgba
    x0, y0, x1, y1 = bbox
    x0 = max(0, x0 - pad_px); y0 = max(0, y0 - pad_px)
    x1 = min(img_rgba.width,  x1 + pad_px); y1 = min(img_rgba.height, y1 + pad_px)
    return img_rgba.crop((x0, y0, x1, y1))

def find_col(df, candidates):
    for c in df.columns:
        if any(str(c).strip().lower().startswith(x) for x in candidates):
            return c
    return None

def extract_filename(cell):
    s = str(cell).strip()
    m = re.search(r'([^/\s]+?\.(png|jpg|jpeg|webp|bmp))', s, re.I)
    return m.group(1) if m else s

def pick_template_pptx(template_folder_id):
    pptx_files = list_in_folder(template_folder_id, r'\.pptx$')
    if not pptx_files:
        raise RuntimeError("No .pptx found in TEMPLATE folder.")
    if TEMPLATE_PPTX_NAME:
        for f in pptx_files:
            if f['title'] == TEMPLATE_PPTX_NAME:
                return f
        raise RuntimeError(f"TEMPLATE_PPTX_NAME='{TEMPLATE_PPTX_NAME}' not found.")
    if len(pptx_files) > 1:
        print("Multiple templates found; using first:", pptx_files[0]["title"])
    return pptx_files[0]

def iter_all_shapes(shapes):
    for shp in shapes:
        yield shp
        if shp.shape_type == MSO_SHAPE_TYPE.GROUP:
            for inner in iter_all_shapes(shp.shapes):
                yield inner

def find_anchor_on_slide(slide, name):
    for shp in iter_all_shapes(slide.shapes):
        if getattr(shp, "name", "").strip() == name:
            return shp
    return None

def validate_ppt_local(ppt_path, expected_slides=None):
    try:
        prs = Presentation(ppt_path)
        actual = len(prs.slides)
    except Exception as e:
        return (False, -1, f"corrupt/unreadable: {type(e).__name__}")
    if expected_slides is not None and actual < expected_slides:
        return (False, actual, f"incomplete slides {actual} < expected {expected_slides}")
    return (True, actual, "ok")

def compute_size_for_area_fraction(slide_w, slide_h, left, top, aspect, target_fraction):
    slide_area = slide_w * slide_h
    desired_area = slide_area * target_fraction

    w = math.sqrt(desired_area * aspect)
    h = math.sqrt(desired_area / aspect)

    max_w = max(1, slide_w - left)
    max_h = max(1, slide_h - top)

    if w > max_w or h > max_h:
        scale = min(max_w / w, max_h / h)
        w *= scale
        h *= scale

    return int(w), int(h)

# NEW: find a subfolder by exact name (case-insensitive match)
def find_subfolder_id(parent_folder_id, subfolder_name):
    subfolder_name_l = subfolder_name.strip().lower()
    folders = drive_list(
        f"'{parent_folder_id}' in parents and trashed=false "
        f"and mimeType='application/vnd.google-apps.folder'"
    )
    for f in folders:
        if str(f.get("title", "")).strip().lower() == subfolder_name_l:
            return f["id"]
    return None


# ---------------- Download template once ----------------
template_folder_id = extract_id_from_url(TEMPLATE_FOLDER_URL)
template_file = pick_template_pptx(template_folder_id)
print("Template PPTX:", template_file["title"])

base_dir = "/content/sheet_ppt_35_40"
os.makedirs(base_dir, exist_ok=True)
template_pptx_path = os.path.join(base_dir, "template.pptx")
template_file.GetContentFile(template_pptx_path)


# ---------------- Read sheet columns (Folder, Verify, PPT) ----------------
col_ppt_idx    = col_letter_to_index(COL_PPT_LINK)
col_folder_idx = col_letter_to_index(COL_FOLDER)
col_verify_idx = col_letter_to_index(COL_PDF_VERIFY)

ppt_vals    = ws.col_values(col_ppt_idx)
folder_vals = ws.col_values(col_folder_idx)
verif_vals  = ws.col_values(col_verify_idx)

max_len = max(len(ppt_vals), len(folder_vals), len(verif_vals))
print("Rows scanned (incl header):", max_len)


# ---------------- Group ONLY "Done" rows by folder id ----------------
groups = {}  # folder_id -> {rows:[], folder_link:str, existing_link:str|None}
for r in range(2, max_len + 1):
    v = verif_vals[r-1].strip() if (r-1) < len(verif_vals) else ""
    if not is_done(v):
        continue  # <-- IMPORTANT: only process "Done"

    folder_link = folder_vals[r-1].strip() if (r-1) < len(folder_vals) else ""
    if not folder_link:
        continue

    try:
        folder_id = extract_id_from_url(folder_link)
    except Exception:
        continue

    groups.setdefault(folder_id, {"rows": [], "folder_link": folder_link, "existing_link": None})
    groups[folder_id]["rows"].append(r)

    # If any "Done" row already has a PPT link, reuse it for that folder
    cur_link = ppt_vals[r-1].strip() if (r-1) < len(ppt_vals) else ""
    if cur_link and (not is_not_required(cur_link)) and (not groups[folder_id]["existing_link"]):
        groups[folder_id]["existing_link"] = cur_link

print("Unique folders found (Done rows only):", len(groups))


processed_folders = 0
skipped_no_work = 0
skipped_missing_files = 0
errors = 0
updated_cells = 0


for folder_id, info in groups.items():
    rows = info["rows"]

    # rows needing fill (PPT Link empty) BUT skip if PPT Link == "Not Req."
    need_rows = []
    for r in rows:
        cur = ppt_vals[r-1].strip() if (r-1) < len(ppt_vals) else ""
        if is_not_required(cur):
            continue
        if not cur:
            need_rows.append(r)

    if not need_rows:
        skipped_no_work += 1
        continue

    print(f"\n=== Folder === {info['folder_link']}")
    print("Rows needing fill (Done only):", need_rows)

    try:
        # 0) If sheet already has a link for this folder, just reuse it (no Drive actions)
        if info["existing_link"]:
            ppt_link_to_use = info["existing_link"]
        else:
            # 1) Cleanup: trash temp in-progress file
            for f in list_by_exact_title(folder_id, TEMP_PPT_NAME):
                f.Trash()

            # 2) Determine expected slide count from XLSX if available
            expected_slides = None
            xlsx_files = list_in_folder(folder_id, r'\.xlsx$')
            if xlsx_files:
                meta_dir = os.path.join(base_dir, f"meta_{folder_id}")
                if os.path.exists(meta_dir):
                    shutil.rmtree(meta_dir)
                os.makedirs(meta_dir, exist_ok=True)

                xlsx_path = os.path.join(meta_dir, "mapping.xlsx")
                xlsx_files[0].GetContentFile(xlsx_path)

                df_raw = pd.read_excel(xlsx_path)
                col_order = find_col(df_raw, ["display order", "display order*"])
                if col_order:
                    mx = pd.to_numeric(df_raw[col_order], errors="coerce").dropna()
                    if not mx.empty:
                        expected_slides = int(mx.max())

            # 3) If final PPT exists, validate and reuse if valid (trash invalid)
            ppt_link_to_use = None
            final_files = list_by_exact_title(folder_id, FINAL_PPT_NAME)
            if final_files:
                best = None
                for f in final_files:
                    chk_dir = os.path.join(base_dir, f"chk_{folder_id}")
                    if os.path.exists(chk_dir):
                        shutil.rmtree(chk_dir)
                    os.makedirs(chk_dir, exist_ok=True)

                    ppt_path = os.path.join(chk_dir, "existing.pptx")
                    f.GetContentFile(ppt_path)

                    ok, actual, reason = validate_ppt_local(ppt_path, expected_slides=expected_slides)
                    print(f"Existing {FINAL_PPT_NAME}: slides={actual}, expected={expected_slides}, status={reason}")

                    if ok:
                        if best is None or actual > best[1]:
                            best = (f, actual)
                    else:
                        # safe delete: corrupt OR (expected known and incomplete)
                        if actual == -1 or expected_slides is not None:
                            f.Trash()

                if best:
                    ppt_link_to_use = drive_file_link(best[0]["id"])

            # 4) If no valid PPT found, create (requires Processed Screenshots folder + xlsx)
            if ppt_link_to_use is None:
                xlsx_files = list_in_folder(folder_id, r'\.xlsx$')
                if not xlsx_files:
                    print("Skip folder: XLSX missing.")
                    skipped_missing_files += 1
                    continue

                processed_subfolder_id = find_subfolder_id(folder_id, PROCESSED_SCREENSHOTS_FOLDER_NAME)
                if not processed_subfolder_id:
                    print(f"Skip folder: subfolder '{PROCESSED_SCREENSHOTS_FOLDER_NAME}' missing.")
                    skipped_missing_files += 1
                    continue

                # list images inside Processed Screenshots
                image_files = list_in_folder(processed_subfolder_id, r'\.(png|jpg|jpeg|webp|bmp)$')
                if not image_files:
                    print(f"Skip folder: no images found in '{PROCESSED_SCREENSHOTS_FOLDER_NAME}'.")
                    skipped_missing_files += 1
                    continue

                xlsx_file = xlsx_files[0]
                print("XLSX:", xlsx_file["title"])
                print(f"Images from folder: {PROCESSED_SCREENSHOTS_FOLDER_NAME} (count={len(image_files)})")

                work = os.path.join(base_dir, f"work_{folder_id}")
                src_dir = os.path.join(work, "src_downloaded")
                tmp_dir = os.path.join(work, "tmp_clean")
                if os.path.exists(work):
                    shutil.rmtree(work)
                os.makedirs(src_dir, exist_ok=True)
                os.makedirs(tmp_dir, exist_ok=True)

                xlsx_path = os.path.join(work, "mapping.xlsx")
                xlsx_file.GetContentFile(xlsx_path)

                df_raw = pd.read_excel(xlsx_path)
                col_order = find_col(df_raw, ["display order", "display order*"])
                col_image = find_col(df_raw, ["question image", "image", "file", "filename"])
                if not col_order or not col_image:
                    print("Skip folder: required columns missing in XLSX.")
                    skipped_missing_files += 1
                    continue

                df = df_raw[[col_order, col_image]].rename(columns={col_order:"display_order", col_image:"question_image"})
                df = df.dropna(subset=["display_order","question_image"]).copy()
                df["display_order"] = df["display_order"].apply(lambda x: int(str(x).strip().split('.')[0]))
                df["src_name"] = df["question_image"].apply(extract_filename)
                df = df.sort_values("display_order").reset_index(drop=True)
                if df.empty:
                    print("Skip folder: mapping empty.")
                    skipped_missing_files += 1
                    continue

                # Build an index of Drive image files in Processed Screenshots folder
                idx = {}
                for f in image_files:
                    idx[str(f["title"]).lower()] = f

                def find_src_file(src_basename):
                    # exact title match
                    f = idx.get(src_basename.lower())
                    if f:
                        return f
                    # stem match ignoring spaces
                    stem = os.path.splitext(src_basename)[0].lower().replace(" ", "")
                    for name_l, fobj in idx.items():
                        if os.path.splitext(name_l)[0].replace(" ", "") == stem:
                            return fobj
                    return None

                # cache downloads by file id
                downloaded = {}  # file_id -> local_path

                prs = Presentation(template_pptx_path)
                template_layout = prs.slides[0].slide_layout

                def ensure_slide(i0):
                    while len(prs.slides) <= i0:
                        prs.slides.add_slide(template_layout)
                    return prs.slides[i0]

                anchor = find_anchor_on_slide(prs.slides[0], ANCHOR_SHAPE_NAME)
                if anchor is None:
                    raise RuntimeError(f"Anchor '{ANCHOR_SHAPE_NAME}' not found in template slide 1.")

                ANCHOR_LEFT = anchor.left
                ANCHOR_TOP  = anchor.top
                slide_w = prs.slide_width
                slide_h = prs.slide_height

                for _, row in df.iterrows():
                    order = int(row["display_order"])
                    src_name = row["src_name"]

                    src_file = find_src_file(src_name)
                    if not src_file:
                        continue

                    fid = src_file["id"]
                    if fid in downloaded:
                        src_local = downloaded[fid]
                    else:
                        ext = os.path.splitext(str(src_file["title"]))[1]
                        if not ext:
                            ext = ".png"
                        # store downloaded file by its Drive id to avoid re-downloading
                        src_local = os.path.join(src_dir, f"{fid}{ext}")
                        src_file.GetContentFile(src_local)
                        downloaded[fid] = src_local

                    cleaned_path = os.path.join(tmp_dir, f"{order}.png")
                    with Image.open(src_local) as im:
                        cleaned = remove_white(im, thr=WHITE_THRESHOLD)
                        cleaned = crop_to_content_rgba(cleaned, pad_px=CROP_PAD_PX)
                        cleaned.save(cleaned_path)

                    # aspect from cleaned image
                    with Image.open(cleaned_path) as im2:
                        w_px, h_px = im2.size
                    if h_px == 0:
                        continue
                    aspect = w_px / h_px

                    w_emu, h_emu = compute_size_for_area_fraction(
                        slide_w, slide_h, ANCHOR_LEFT, ANCHOR_TOP, aspect, TARGET_FRACTION
                    )

                    slide = ensure_slide(order - 1)
                    slide.shapes.add_picture(cleaned_path, ANCHOR_LEFT, ANCHOR_TOP, width=w_emu, height=h_emu)

                local_final = os.path.join(work, FINAL_PPT_NAME)
                prs.save(local_final)

                # upload TEMP then rename to FINAL (restart-safe)
                for f in list_by_exact_title(folder_id, TEMP_PPT_NAME):
                    f.Trash()

                up = drive.CreateFile({'title': TEMP_PPT_NAME, 'parents': [{'id': folder_id}]})
                up.SetContentFile(local_final)
                up.Upload(param={'supportsAllDrives': True})

                up['title'] = FINAL_PPT_NAME
                up.Upload(param={'supportsAllDrives': True})

                ppt_link_to_use = drive_file_link(up["id"])
                print("Created PPT:", ppt_link_to_use)

        # Fill ONLY column X for rows needing it (Done rows only; Not Req. excluded)
        ws.batch_update([{"range": f"{COL_PPT_LINK}{r}", "values": [[ppt_link_to_use]]} for r in need_rows])
        updated_cells += len(need_rows)
        processed_folders += 1
        time.sleep(SLEEP_BETWEEN_FOLDER_SEC)

    except Exception as e:
        errors += 1
        print("ERROR:", repr(e))
        continue


print("\n===== DONE =====")
print("Folders processed:", processed_folders)
print("Folders skipped (no empty PPT link in Done rows or only Not Req.):", skipped_no_work)
print("Folders skipped (missing xlsx/processed folder/images):", skipped_missing_files)
print("Cells updated (only col X):", updated_cells)
print("Errors:", errors)